# TruffleHog Secret detection
stages:
  - trufflehog_scan
  - upload

.trufflehog_secret_detection:
  image:
    name: docker:latest
    pull_policy: if-not-present
  tags:
    - backoffice-docker
  stage: trufflehog_scan
  services:
    - docker:24.0.5-dind
  script:
    - apk add --no-cache curl git
    - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
    - trufflehog git file://. --no-verification --json > trufflehog-report.json
  artifacts:
    paths:
      - trufflehog-report.json
    expire_in: 1 week

.upload_trufflehog_to_defectdojo_template:
  stage: upload
  image: 
    name: curlimages/curl:latest
    pull_policy: if-not-present
  variables:
    DOCKER_NETWORK_MODE: "host"
  needs: [trufflehog_scan]
  tags:
    - docker
  script:
    - |
      curl -X POST "${DEFECTDOJO_URL}/api/v2/import-scan/" \
        -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
        -F 'scan_type=Trufflehog Scan' \
        -F "file=@trufflehog-report.json" \
        -F "product_name=$CI_PROJECT_PATH_SLUG" \
        -F "engagement_name=CI Pipeline" \
        -F 'auto_create_context=true' \
        -F "product_type_name=Repository" \
        -F 'active=true' \
        -F 'verified=true'
  dependencies:
    - trufflehog_scan

